### ISSUE TITLE
GET_COMPONENTS method does not break up INCLUDES

### ISSUE THREAD

**Issue by zenrosadira** [Keller-Michael/markdown_from_table_or_structure#1]
Hi Michael, nice tool.
I noticed that you use the `->get_components( )` method to get the fields of a structure or table, but it doesn't unpack possible include structures. I suggest accessing directly to components list using instance attribute `->components`, then you can obtain field type descriptor using `structdescr->get_component_type( component-name )`. However, I don't know if these attributes/methods are publicly released for SAP BTP.

**Comment by Keller-Michael** [comment]
Hi Marco,

good note. Right off I didn't find an instance attribute "COMPONENTS" in class CL_ABAP_STRUCTDESCR. But while searching I noticed GET_INCLUDED_VIEW method. Maybe that's a good starting point. If you use this method with level value "1" I guess you get the include names and with a loop and some additional CL_ABAP_STRUCTDESCR/GET_COMPONENTS() calls we can break up includes. That's my idea so far...

At the moment I just don't have enough time to take a closer look. Maybe you want to do some research with this method on BTP?

**Comment by zenrosadira** [comment]
I did some research on the BTP Trial and `components` instance seems usable (I used it in a custom test class where ABAP language version is "ABAP for Cloud Development")

<img src="https://imgtr.ee/images/2023/04/14/y8oem.png" alt="y8oem.png" border="0" width="405" height="270"/>

Despite this, `get_included_view( )` method is more suitable, so I would use this.
As reported in the method documentation:

> If GET_INCLUDED_VIEW is called without specifying a level, the fully included view is returned, so that all includes are textually expanded.

The resulting type (`included_view`) is a table with `name` and `type` fields, therefore similar, and simpler, than the one resulting from the method `get_components( )`, so no additional code is required.

**Comment by Keller-Michael** [comment]
Thanks to your research results, I implemented a solution so that included structures are now resolved. Please have a look if everything is now fine and I will then close this issue with your ok. Many thanks in advance.

**Comment by zenrosadira** [comment]
All good, I have created a deeply nested structure and all components have been written by markdown.
